# Generated by Django 5.2.14 on 2026-05-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField(default=0)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='urunler/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_ad', models.CharField(max_length=100)),
                ('musteri_email', models.EmailField(max_length=254)),
                ('miktar', models.IntegerField(default=1)),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.urun')),
            ],
        ),
    ]
